/*
 *
 *  $Id$
 *
 *  This file is part of the Virtual Leaf.
 *
 *  VirtualLeaf is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  VirtualLeaf is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with the Virtual Leaf.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright 2010 Roeland Merks.
 *
 */

// WARNING: This file is automatically generated by make_parameter_source.pl. Do not edit.
// Do not edit. All edits will be discarded.


#ifndef _PARAMETER_H_
#define _PARAMETER_H_
#include <iostream>
#include <vector>

using namespace std;

 class Parameter {
		
 public: 
   Parameter();
   ~Parameter();
   void CleanUp(void);
   void Read(const char *filename);
   void Write(ostream &os) const;
   //void XMLAdd(xmlNode *root) const;
   //void XMLRead(xmlNode *root);
   void AssignValToPar(const char *namec, const char *valc);
   void AssignValArrayToPar(const char *namec, vector<double> valarray);
  int SEED;
  int NVX;
  int NVY;
  int MCS;
  int TARGETVOLUME;
  double CELLFORCE;
  double VOXSIZE;
  int NRINC;
  int MAXNRITER;
  double ACCURACY;
  double YOUNGS;
  double POISSON;
  bool GLOBALSTRAIN;
  double LOADANGLE;
  double LOAD;
  double MOTILITY;
  double INELASTICITY;
  double NOSTICKJCM;
  double NOSTICKJCC;
  double LAMBDADUR;
  double THRESHOLDSTIFF;
  double STIFFSENSITIVITY;
  double STIFFENINGSTIFF;
  bool COMPRESSINGSTIFF;
  double LAMBDADISS;
  double COLLAGEN;
  int PIXPERVOX;
  int LINEWIDTH;
  bool CELLFORCES;
  bool DUROTAXIS;
  int STRIDE;
  int WSTRIDE;
  bool STRAINFIELD;
  bool FORCEFIELD;
  bool PRINCFIELD;
  int WHICHSIGMF;
  bool NODECONNECTION;
  bool CELLCOLOUR;
  bool ONECELL;
  bool TWOCELL;
  int DISTWOCELLS;
  bool CELLCOL;
  bool READCELLS;
  double CELLDENSITY;
  int BOUNDARYDIS;
  int NRcf;
  bool COLORBAR;
  double MAXCOLORBAR;
  int WIDTHCOLORBAR;
  bool WRATIOPA;
  bool WLENGTH;
  bool WAREA;
  bool WSQDIS;
  bool WECC;
  bool WANGLE;
  bool WSIGMA;
  bool WTWOCELLCONTACT;
  bool WTWOCELLANGLECM;
 private:
 };

 ostream &operator<<(ostream &os, Parameter &p);
 const char *sbool(const bool &p);


#endif
